# Generated by Django 4.0.1 on 2022-01-23 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(blank=True, max_length=256, null=True)),
                ('student_type', models.CharField(blank=True, choices=[('bachelor', 'Bakalavr'), ('bagistr', 'Magistr')], max_length=18, null=True)),
                ('payed_sum', models.FloatField(blank=True, null=True)),
                ('contract_sum', models.FloatField(blank=True, null=True)),
                ('OTM', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminauth.otm')),
                ('patrons', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminauth.patron')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
