# Generated by Django 4.0.1 on 2022-01-23 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminauth', '0002_otm_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='patrons',
        ),
        migrations.AddField(
            model_name='patron',
            name='payed_for_student',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patron',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminauth.student'),
        ),
    ]
