# Generated by Django 4.0.1 on 2022-01-23 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminauth', '0003_remove_student_patrons_patron_payed_for_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patron',
            name='payed_for_student',
        ),
        migrations.RemoveField(
            model_name='patron',
            name='student',
        ),
        migrations.CreateModel(
            name='PatronToStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('payed', models.FloatField(default=0, null=True)),
                ('paton', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminauth.patron')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminauth.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
