# Generated by Django 4.0.1 on 2022-01-23 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminauth', '0004_remove_patron_payed_for_student_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patrontostudent',
            old_name='paton',
            new_name='patron',
        ),
    ]
