# Generated by Django 4.0.1 on 2022-01-23 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminauth', '0005_rename_paton_patrontostudent_patron'),
    ]

    operations = [
        migrations.AddField(
            model_name='patron',
            name='condition',
            field=models.CharField(blank=True, choices=[('recieved', 'Qabul qilindi'), ('new', 'Yangi'), ('moderation', 'Moderatsiyada')], default='moderation', max_length=18, null=True),
        ),
    ]
