# Generated by Django 4.0.1 on 2022-01-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('patron_type', models.CharField(blank=True, choices=[('Jismoniy', 'Jismoniy'), ('Yuridik', 'Yuridik')], default=None, max_length=10, null=True)),
                ('full_name', models.CharField(blank=True, max_length=256, null=True)),
                ('phone', models.CharField(max_length=13, unique=True, verbose_name='phone number')),
                ('payment', models.FloatField(blank=True, null=True)),
                ('name_company', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
