# Generated by Django 4.0.1 on 2022-01-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='condition',
            field=models.CharField(blank=True, choices=[('recieved', 'Qabul qilindi'), ('new', 'Yangi')], default=None, max_length=40, null=True),
        ),
    ]
